title: A A Siddique
logo: /assets/img/ashikul-image.jpg

#show_downloads: true
theme: jekyll-theme-minimal

# Author information
author:
  name: Md Ashikul Aziz Siddique
  bio: Computer Vision Researcher | Data Science Enthusiast | Technical Support Engineer
  location: 180/1 West Shewrapara, Mirpur-1216, Dhaka, Bangladesh
  email: mdashilulaziz@gmail.com
  Phone: +8801767212232

# Social media links
social:
  - title: LinkedIn
    url: https://www.linkedin.com/in/ashikulazizsiddique/
  - title: GitHub
    url: https://github.com/ashikulazizsiddique
  - title: Twitter
    url: https://twitter.com/ashikulaziz
  # Add more social media links as needed


