title: A A Siddique
logo: /assets/img/ashikul-image.jpg
<h3 align="center">Computer Vision Researcher | Technical Support Engineer</h3>
<h3 align="left">Connect with me:</h3>
<p align="left">
<a href="https://twitter.com/ashikulaziz" target="blank"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/twitter.svg" alt="ashikulaziz" height="30" width="40" /></a>
<a href="https://linkedin.com/in/ashikulazizsiddique" target="blank"><img align="center" src="https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/linked-in-alt.svg" alt="ashikulazizsiddique" height="30" width="40" /></a>
</p>

#show_downloads: true
theme: jekyll-theme-minimal

# Author information
author:
  name: Md Ashikul Aziz Siddique
  bio: Computer Vision Researcher | Data Science Enthusiast | Technical Support Engineer
  location: 180/1 West Shewrapara, Mirpur-1216, Dhaka, Bangladesh
  email: mdashilulaziz@gmail.com
  Phone: +8801767212232

# Social media links
social:
  - title: LinkedIn
    url: https://www.linkedin.com/in/ashikulazizsiddique/
  - title: GitHub
    url: https://github.com/ashikulazizsiddique
  - title: Twitter
    url: https://twitter.com/ashikulaziz
  # Add more social media links as needed


